In [2]:
import pandas as pd

In [3]:
df = pd.read_json("/kaggle/input/datasets/sanjanbm/train-json/train.json")

## Woking with JSON

In [4]:
df.head()

      id      cuisine                                        ingredients
0  10259        greek  [romaine lettuce, black olives, grape tomatoes...
1  25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2  20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3  22213       indian                [water, vegetable oil, wheat, salt]
4  13162       indian  [black pepper, shallots, cornflour, cayenne pe...

In [5]:
df.info

<bound method DataFrame.info of           id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]>

In [6]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-23,1771804801,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-23,1771804801,0.0404
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-23,1771804801,0.6940
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-23,1771804801,0.9010
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-23,1771804801,4.1500
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-23,1771804801,2.6300
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-23,1771804801,0.1770
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-23,1771804801,0.2080
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-23,1771804801,0.2810
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-23,1771804801,0.2810

In [7]:
df = pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

In [8]:
df.head()

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-23,1771804801,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-23,1771804801,0.0404
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-23,1771804801,0.6940
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-23,1771804801,0.9010
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-02-23,1771804801,4.1500

In [9]:
df.info

<bound method DataFrame.info of                              provider  \
INR  https://www.exchangerate-api.com
AED  https://www.exchangerate-api.com
AFN  https://www.exchangerate-api.com
ALL  https://www.exchangerate-api.com
AMD  https://www.exchangerate-api.com
..                                ...
YER  https://www.exchangerate-api.com
ZAR  https://www.exchangerate-api.com
ZMW  https://www.exchangerate-api.com
ZWG  https://www.exchangerate-api.com
ZWL  https://www.exchangerate-api.com

                          WARNING_UPGRADE_TO_V6  \
INR  https://www.exchangerate-api.com/docs/free
AED  https://www.exchangerate-api.com/docs/free
AFN  https://www.exchangerate-api.com/docs/free
ALL  https://www.exchangerate-api.com/docs/free
AMD  https://www.exchangerate-api.com/docs/free
..                                          ...
YER  https://www.exchangerate-api.com/docs/free
ZAR  https://www.exchangerate-api.com/docs/free
ZMW  https://www.exchangerate-api.com/docs/free
ZWG  https://www.exchangerate-api.com/docs/free
ZWL  https://www.exchangerate-api.com/docs/free

                                      terms base       date  \
INR  https://www.exchangerate-api.com/terms  INR 2026-02-23
AED  https://www.exchangerate-api.com/terms  INR 2026-02-23
AFN  https://www.exchangerate-api.com/terms  INR 2026-02-23
ALL  https://www.exchangerate-api.com/terms  INR 2026-02-23
AMD  https://www.exchangerate-api.com/terms  INR 2026-02-23
..                                      ...  ...        ...
YER  https://www.exchangerate-api.com/terms  INR 2026-02-23
ZAR  https://www.exchangerate-api.com/terms  INR 2026-02-23
ZMW  https://www.exchangerate-api.com/terms  INR 2026-02-23
ZWG  https://www.exchangerate-api.com/terms  INR 2026-02-23
ZWL  https://www.exchangerate-api.com/terms  INR 2026-02-23

     time_last_updated   rates
INR         1771804801  1.0000
AED         1771804801  0.0404
AFN         1771804801  0.6940
ALL         1771804801  0.9010
AMD         1771804801  4.1500
..                 ...     ...
YER         1771804801  2.6300
ZAR         1771804801  0.1770
ZMW         1771804801  0.2080
ZWG         1771804801  0.2810
ZWL         1771804801  0.2810

[166 rows x 7 columns]>

In [10]:
df.isnull()

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,False,False,False,False,False,False,False
AED,False,False,False,False,False,False,False
AFN,False,False,False,False,False,False,False
ALL,False,False,False,False,False,False,False
AMD,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
YER,False,False,False,False,False,False,False
ZAR,False,False,False,False,False,False,False
ZMW,False,False,False,False,False,False,False
ZWG,False,False,False,False,False,False,False
ZWL,False,False,False,False,False,False,False

In [11]:
df.isnull().sum()

provider                 0
WARNING_UPGRADE_TO_V6    0
terms                    0
base                     0
date                     0
time_last_updated        0
rates                    0
dtype: int64

## Working with SQL
https://www.kaggle.com/datasets/hashtagkehl/worldsql

In [12]:
pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.9/11.9 MB 85.4 MB/s eta 0:00:0000:010:01
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (setup.py) ... done
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp312-cp312-linux_x86_64.whl size=247950 sha256=7579ea91e2c1232064ceb789b810e27452ffebaf5896c70d5f4833efeb76f2ec
  Stored in directory: /root/.cache/pip/wheels/03/17/fa/d7604c72dd3dd6d3eb3d249abf36cc532c9a9b4354b8f1bc4f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9
Note: you may need to restart the kernel to use updated packages.

In [13]:
import mysql.connector

In [ ]:
# This has to be done through xampp, or any softwares that allows sql to run and store

conn = mysql.connector.connect(hsot='localhost', user="root", password='', database='world')

In [ ]:
pd.read_sql_query("SELECT * FROM city", conn)

In [ ]:
pd.read_sql("/kaggle/input/datasets/hashtagkehl/worldsql/sqlpractice.sql", conn)

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_sql.html

To read the data from sql, documentation